name: Train Timetable Download

on:
  push:
    branches:
      - main  # Adjust this to the branch where you want the pipeline to trigger on code changes
  pull_request:
    branches:
      - main
  schedule:
    # Run every day at 1 AM (adjust as needed)
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run timetable script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
        run: |
          python your_script.py
